---
linters-settings:
  misspell:
    locale: US

linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - funlen
    - goconst
    - gosec
    - misspell
    - unconvert
    - prealloc
  disable:
    - errcheck
    - ineffassign

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - funlen

linters-settings:
  errorlint:
    # Report non-wrapping error creation using fmt.Errorf
    errorf: false
  funlen:
    lines: 120
    statements: 50
