## SPDX-FileCopyrightText: 2016 Comcast Cable Communications Management, LLC
## SPDX-License-Identifier: Apache-2.0
apiVersion: v1
data:
  petasos.yaml: |
    # The unique fully-qualified-domain-name of the server.  It is provided to
    # the X-petasos-Server header for showing what server fulfilled the request
    # sent.
    # (Optional)
    server: "petasos"

    ########################################
    #   Labeling/Tracing via HTTP Headers Configuration
    ########################################

    # Provides this build number to the X-petasos-Build header for
    # showing machine version information.  The build number SHOULD
    # match the scheme `version-build` but there is not a strict requirement.
    # (Optional)
    build: "0.1.4"

    # Provides the region information to the X-petasos-Region header
    # for showing what region this machine is located in.  The region
    # is arbitrary and optional.
    # (Optional)
    region: "east"

    # Provides the flavor information to the X-petasos-Flavor header
    # for showing what flavor this machine is associated with.  The flavor
    # is arbitrary and optional.
    # (Optional)
    flavor: "mint"

    ##############################################################################
    # WebPA Service configuration
    ##############################################################################

    # For a complete view of the service config structure,
    # checkout https://godoc.org/github.com/xmidt-org/webpa-common/v2/server#WebPA

    ########################################
    #   primary endpoint Configuration
    ########################################

    # primary defines the details needed for the primary endpoint.  The
    # primary endpoint accepts the events from petasos (typically).
    # define https://godoc.org/github.com/xmidt-org/webpa-common/v2/server#Basic
    primary:
      # address provides the port number for the endpoint to bind to.
      # ":443" is ideal, but may require some special handling due to it being
      # a reserved (by the kernel) port.
      address: "{{ .Values.petasos.address.host }}:{{ .Values.petasos.address.port }}"
      # HTTPS/TLS
      #
      # certificateFile provides the public key and CA chain in PEM format if
      # TLS is used.  Note: the certificate needs to match the fqdn for clients
      # to accept without issue.
      #
      # keyFile provides the private key that matches the certificateFile
      # (Optional)
      # certificateFile: "/etc/petasos/public.pem"
      # keyFile: "/etc/petasos/private.pem"
    ########################################
    #   health endpoint Configuration
    ########################################

    # health defines the details needed for the health check endpoint.  The
    # health check endpoint is generally used by services (like AWS Route53
    # or consul) to determine if this particular machine is healthy or not.
    # define https://godoc.org/github.com/xmidt-org/webpa-common/v2/server#Health
    health:
      # address provides the port number for the endpoint to bind to.
      # ":80" is ideal, but may require some special handling due to it being
      # a reserved (by the kernel) port.
      address: "{{ .Values.health.address.host }}:{{ .Values.health.address.port }}"

      # logInterval appears to be present from before we had formal metrics
      # (Deprecated)
      # logInterval: "60s"
      # options appears to be present from before we had formal metrics
      # (Deprecated)
      # options:
      #  - "PayloadsOverZero"
      #  - "PayloadsOverHundred"
      #  - "PayloadsOverThousand"
      #  - "PayloadsOverTenThousand"

    ########################################
    #   Debugging/pprof Configuration
    ########################################

    # pprof defines the details needed for the pprof debug endpoint.
    # define https://godoc.org/github.com/xmidt-org/webpa-common/v2/server#Basic
    # (Optional)
    pprof:
      # address provides the port number for the endpoint to bind to.
      address: "{{ .Values.pprof.address.host }}:{{ .Values.pprof.address.port }}"

    ########################################
    #   Metrics Configuration
    ########################################

    # metric defines the details needed for the prometheus metrics endpoint
    # define https://godoc.org/github.com/xmidt-org/webpa-common/v2/server#Metric
    # (Optional)
    metric:
      # address provides the port number for the endpoint to bind to.  Port 6404
      # was chosen because it does not conflict with any of the other prometheus
      # metrics or other machines in the xmidt cluster.  You may use any port you
      # wish.
      address: "{{ .Values.metric.address.host }}:{{ .Values.metric.address.port }}"

      # metricsOptions provides the details needed to configure the prometheus
      # metric data.  Metrics generally have the form:
      #
      # {namespace}_{subsystem}_{metric}
      #
      # so if you use the suggested value below, your metrics are prefixed like
      # this:
      #
      # xmidt_petasos_{metric}
      #
      # (Optional)
      metricsOptions:
        # namespace is the namespace of the metrics provided
        # (Optional)
        namespace: "xmidt"
        # subsystem is the subsystem of the metrics provided
        # (Optional)
        subsystem: "petasos"

    ########################################
    #   Logging Related Configuration
    ########################################

    # log configures the logging subsystem details
    log:
      # file is the name of the most recent log file.  If set to "stdout" this
      # will log to os.Stdout.
      # (Optional) defaults to os.TempDir()
      # file: "/var/log/petasos/petasos.log"
      file: "stdout"

      # level is the logging level to use - INFO, DEBUG, WARN, ERROR
      # (Optional) defaults to ERROR
      level: "DEBUG"

      # maxsize is the maximum file size in MB
      # (Optional) defaults to max 100MB
      maxsize: 50

      # maxage is the maximum number of days to retain old log files
      # (Optional) defaults to ignore age limit (0)
      maxage: 30

      # maxbackups is the maximum number of old log files to retain
      # (Optional) defaults to retain all (0)
      maxbackups: 10

      # json is a flag indicating whether JSON logging output should be used.
      # (Optional) defaults to false
      json: true

    ########################################
    #   Service Discovery Configuration
    ########################################

    # service configures the server for service discovery.
    # defined https://godoc.org/github.com/xmidt-org/webpa-common/v2/service/servicecfg#Options
    # this is required, consul or fixed must be used.
    service:
      # defaultScheme, used for the registered servers for communication.
      # (Optional) defaults to https
      defaultScheme: http

      # vnodeCount used for consistent hash calculation github.com/billhathaway/consistentHash.
      # number of virtual nodes. should be a prime number
      # it is a tradeoff of memory and ~ log(N) speed versus how well the hash spreads
      # (Optional) defaults to 211
      vnodeCount: 211

      # disableFilter disables filtering.
      # (Deprecated) does not do anything
      # disableFilter: false

      # fixed is the list of servers in the datacenter.
      # (Optional) default to empty list
      fixed:
        - http://talaria:6200
kind: ConfigMap
metadata:
  labels:
    app: xmidt-app
  name: petasos-config
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    component: petasos
    release: petasos
  name: petasos
spec:
  clusterIP: None
  ports:
    - name: primary
      port: {{ .Values.petasos.address.port }}
      protocol: TCP
    - name: health
      port: {{ .Values.health.address.port }}
      protocol: TCP
    - name: pprof
      port: {{ .Values.pprof.address.port }}
      protocol: TCP
    - name: metric
      port: {{ .Values.metric.address.port }}
      protocol: TCP
  selector:
    app: xmidt-app-petasos
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: petasos
  labels:
    app: xmidt-app-petasos
spec:
  selector:
    matchLabels:
      app: xmidt-app-petasos
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  serviceName: xmidt-app-petasos
  template:
    metadata:
      labels:
        app: xmidt-app-petasos
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - xmidt-app-petasos
      volumes:
        - name: petasos-config
          projected:
            sources:
              - configMap:
                  name: petasos-config
                  items:
                    - key: petasos.yaml
                      path: petasos.yaml
                      mode: 0755
      securityContext:
        runAsNonRoot: false
        runAsUser: 999
        supplementalGroups: [999]
      containers:
        - image: {{ .Values.petasos.image }}
          name: petasos
          ports:
            - containerPort: {{ .Values.petasos.address.port }}
              protocol: TCP
            - containerPort: {{ .Values.health.address.port }}
              protocol: TCP
            - containerPort: {{ .Values.pprof.address.port }}
              protocol: TCP
            - containerPort: {{ .Values.metric.address.port }}
              protocol: TCP
          volumeMounts:
            - name: petasos-config
              mountPath: "/etc/petasos"
              readOnly: true
      {{ if (.Values.imagePullSecretName) }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretName }}}
      {{ end }}